[general]
import = [
    # "~/.config/alacritty/themes/catppuccin_mocha.toml",
    "~/.config/alacritty/themes/themes/tokyo_night.toml",
]

[window]
opacity = 0.90
blur = true
padding = { x = 8, y = 8 }
dynamic_padding = false

[font]
normal = { family = "Maple Mono NF CN", style = "Regular" }
size = 16.0
offset = { x = 0, y = 2 }


[scrolling]
history = 100000
multiplier = 2

[selection]
save_to_clipboard = true
