# zish macOS bootstrap package list.
# Install with: brew bundle --file ./Brewfile

# CLI tools
brew "bat"
brew "btop"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "htop"
brew "jq"
brew "lazygit"
brew "mise"
brew "neovim"
brew "nvm"
brew "pnpm"
brew "ripgrep"
brew "tmux"
brew "uv"
brew "yq"
brew "zoxide"
brew "dust"

# Apps
cask "1password"
cask "bruno"
cask "codex"
cask "contexts"
cask "feishu"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "iina"
cask "input-source-pro"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "keka"
cask "macshot"
cask "mole-app"
cask "neteasemusic"
cask "obsidian"
cask "orbstack"
cask "raycast"
cask "shortcat"
cask "slack"
cask "stats"
cask "tencent-meeting"
cask "visual-studio-code"
cask "wechat"
cask "wetype"
cask "zed"
cask "zotero"
